// <auto-generated />
using DockerWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NormalWebAPI.Migrations
{
    [DbContext(typeof(BykeStoresContext))]
    partial class BykeStoresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DockerWebAPI.Models.Brand", b =>
                {
                    b.Property<string>("brandId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("brand_id");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("brand_name");

                    b.HasKey("brandId")
                        .HasName("primary_key");

                    b.ToTable("brands", "production");
                });
#pragma warning restore 612, 618
        }
    }
}
